#.travis.yml

language: node_js
node_js:
  - "7.4"

branches:
  only:
    - master

before_script:
  - npm install -g firebase-tools
  - npm install -g ionic cordova

script:
  - npm run ionic:build --prod

after_success:
  - firebase deploy --token $FIREBASE_TOKEN

notifications:
  email:
    on_failure: change
    on_success: change